apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deployment
  labels:
    app: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
      - name: notebook
        image: igelo/notebook-app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-service
spec:
  type: NodePort
  selector:
    app: notebook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080